// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Repository;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(MyStepDbContext))]
    partial class MyStepDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.LearningObjective", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("SkillId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("learning_objectives", (string)null);
                });

            modelBuilder.Entity("Models.PathItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("paths", (string)null);
                });

            modelBuilder.Entity("Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PathId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PathId");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SelectedPathId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SelectedPathId");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("Models.StudentLearningObjective", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<int>("LearningObjectiveId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Score")
                        .HasColumnType("double precision");

                    b.HasKey("StudentId", "LearningObjectiveId");

                    b.HasIndex("LearningObjectiveId");

                    b.ToTable("student_learning_objectives", (string)null);
                });

            modelBuilder.Entity("Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MainSkillId")
                        .HasColumnType("integer");

                    b.Property<int>("PathId")
                        .HasColumnType("integer");

                    b.Property<Vector>("SearchVector")
                        .IsRequired()
                        .HasColumnType("vector(4096)");

                    b.Property<string>("TaskData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("MainSkillId");

                    b.HasIndex("PathId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("Models.TaskPrerequisite", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("LearningObjectiveId")
                        .HasColumnType("integer");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("TaskId", "LearningObjectiveId");

                    b.HasIndex("LearningObjectiveId");

                    b.ToTable("task_prerequisites", (string)null);
                });

            modelBuilder.Entity("Models.TaskTarget", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("LearningObjectiveId")
                        .HasColumnType("integer");

                    b.HasKey("TaskId", "LearningObjectiveId");

                    b.HasIndex("LearningObjectiveId");

                    b.ToTable("task_targets", (string)null);
                });

            modelBuilder.Entity("Models.LearningObjective", b =>
                {
                    b.HasOne("Models.Skill", "Skill")
                        .WithMany("LearningObjectives")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Models.Skill", b =>
                {
                    b.HasOne("Models.PathItem", "Path")
                        .WithMany("Skills")
                        .HasForeignKey("PathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Path");
                });

            modelBuilder.Entity("Models.Student", b =>
                {
                    b.HasOne("Models.PathItem", "SelectedPath")
                        .WithMany()
                        .HasForeignKey("SelectedPathId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SelectedPath");
                });

            modelBuilder.Entity("Models.StudentLearningObjective", b =>
                {
                    b.HasOne("Models.LearningObjective", "LearningObjective")
                        .WithMany()
                        .HasForeignKey("LearningObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Student", "Student")
                        .WithMany("StudentLearningObjectives")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningObjective");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Models.TaskItem", b =>
                {
                    b.HasOne("Models.Skill", "MainSkill")
                        .WithMany()
                        .HasForeignKey("MainSkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Models.PathItem", "Path")
                        .WithMany()
                        .HasForeignKey("PathId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainSkill");

                    b.Navigation("Path");
                });

            modelBuilder.Entity("Models.TaskPrerequisite", b =>
                {
                    b.HasOne("Models.LearningObjective", "LearningObjective")
                        .WithMany()
                        .HasForeignKey("LearningObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.TaskItem", "Task")
                        .WithMany("Prerequisites")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningObjective");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Models.TaskTarget", b =>
                {
                    b.HasOne("Models.LearningObjective", "LearningObjective")
                        .WithMany()
                        .HasForeignKey("LearningObjectiveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.TaskItem", "Task")
                        .WithMany("Targets")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningObjective");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Models.PathItem", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("Models.Skill", b =>
                {
                    b.Navigation("LearningObjectives");
                });

            modelBuilder.Entity("Models.Student", b =>
                {
                    b.Navigation("StudentLearningObjectives");
                });

            modelBuilder.Entity("Models.TaskItem", b =>
                {
                    b.Navigation("Prerequisites");

                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
