### Create Task Item
POST https://localhost:7147/api/taskItems
Content-Type: application/json

{
  "pathId": 5,
  "mainSkillId": 3,
  "taskData":{

"Example": "task description"
    },
      "searchVector": [0.12, 0.55, 0.78, 0.91]
}

###
GET https://localhost:7147/api/taskItem 